FROM node:10 as builder
WORKDIR /app
COPY package-lock.json package.json ./
RUN npm install
COPY .env .
COPY .babelrc .
COPY .eslintrc .
COPY sassHelper.js .
COPY webpack.config.server.js .
COPY webpack.config.client.js .
COPY src ./src
RUN npm run build

FROM node:10
WORKDIR /usr/src/app
COPY --from=builder /app/dist .
RUN npm install --only=production

EXPOSE 80
CMD ["npm", "start"]
