version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  production:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    environment:
      - PORT=8000
      - NODE_ENV_DOCKER=true
      - DATABASE_URL=mongodb://db/react-boilerplate
    container_name: fullstack-production
    ports:
      - 9000:9000
    command: npm start
    depends_on:
      - db

  storybook:
    build:
      context: .
      dockerfile: ./Dockerfile.storybook
    container_name: storybook-production
    ports:
      - 7001:80
    command: npm start

  coverage:
    build:
      context: .
      dockerfile: ./Dockerfile.coverage
    container_name: coverage
    ports:
      - 7002:80
    command: npm start

  development:
    build:
      context: .
    container_name: development
    environment:
#      - PORT=8000
      - NODE_ENV_DOCKER=true
      - DATABASE_URL=mongodb://db/react-boilerplate
    ports:
      - 5001:5001
#      - 8001:8000
    volumes:
      - ./src:/app/src
    command: npm run start
    depends_on:
      - db
